install.packages("devtools")
library(devtools)
install.packages("traits")
library("traits")
#make a species list
sp <- c("Lavandula stoechas", "Carpobrotus edulis", "Rhododendron ponticum", "Alkanna lutea", "Anchusa arvensis")
sp.1
sp.2<-c("Bougainvillea glabra","Thuja orientalis","Pinus halepensis")
#Ejemplo que funciona
is_native(sp.2[3],where = "Spain", region = "europe")
#Ejemplo que no encuentra la especie en la base de datos
is_native(sp.2[1],where = "Spain", region = "europe")
#Y aquí el error recurrente
is_native(sp.2[2],where = "Spain", region = "europe")


#ask in which countries the first species is native by querying in Flora Europaea
fe_native(sp[1])
?fe_native #to see the help page.

#use sapply for querying all species at once
sapply(sp, fe_native, simplify = FALSE)

#ask if the first species is native in a particular region
is_native(sp[1], where = "Spain", region = "europe")
?is_native #to see the help page and country names used

#or all species at once
sapply(sp, is_native, where = "Continental US", region = "america")
sapply(sp, is_native, where = "Spain", region = "europe")

#for america I am calling itis_native function from taxize package.

sp.1<-Species$Species
sp.1<-as.character(sp.1)
Species.1<-Species[,1]
sapply(sp.1, is_native, where = "Spain", region = "europe")
is_native(sp.1[3], where = "Spain", region = "europe")
sp.1
length(sp.1)
for (n in 1:(length(sp.1))){
is_native(sp.1[n], where = "Spain", region = "europe")
}
is_native(sp.1[14], where = "Spain", region = "europe")
is_native(sp.1[15], where = "Spain", region = "europe")
is_native(sp.1[16], where = "Spain", region = "europe")
is_native(sp.1[17], where = "Spain", region = "europe")
is_native(sp.1[18], where = "Spain", region = "europe")
is_native(sp.1[19], where = "Spain", region = "europe")
is_native(sp.1[20], where = "Spain", region = "europe")
is_native(sp.1[21], where = "Spain", region = "europe")
is_native(sp.1[22], where = "Spain", region = "europe")
is_native(sp.1[23], where = "Spain", region = "europe")
is_native(sp.1[24], where = "Spain", region = "europe")
is_native(sp.1[25], where = "Spain", region = "europe")
is_native(sp.1[26], where = "Spain", region = "europe")
is_native(sp.1[27], where = "Spain", region = "europe")
is_native(sp.1[28], where = "Spain", region = "europe")
is_native(sp.1[29], where = "Spain", region = "europe")
is_native(sp.1[30], where = "Spain", region = "europe")
is_native(sp.1[31], where = "Spain", region = "europe")
is_native(sp.1[32], where = "Spain", region = "europe")
is_native(sp.1[33], where = "Spain", region = "europe")
is_native(sp.1[34], where = "Spain", region = "europe")
is_native(sp.1[35], where = "Spain", region = "europe")
is_native(sp.1[36], where = "Spain", region = "europe")
is_native(sp.1[37], where = "Spain", region = "europe")
is_native(sp.1[38], where = "Spain", region = "europe")
is_native(sp.1[39], where = "Spain", region = "europe")
is_native(sp.1[40], where = "Spain", region = "europe")
is_native(sp.1[41], where = "Spain", region = "europe")
is_native(sp.1[42], where = "Spain", region = "europe")
is_native(sp.1[43], where = "Spain", region = "europe")
is_native(sp.1[44], where = "Spain", region = "europe")
is_native(sp.1[45], where = "Spain", region = "europe")
is_native(sp.1[46], where = "Spain", region = "europe")
is_native(sp.1[47], where = "Spain", region = "europe")
is_native(sp.1[48], where = "Spain", region = "europe")
is_native(sp.1[49], where = "Spain", region = "europe")
is_native(sp.1[50], where = "Spain", region = "europe")
is_native(sp.1[51], where = "Spain", region = "europe")
is_native(sp.1[52], where = "Spain", region = "europe")
is_native(sp.1[53], where = "Spain", region = "europe")
is_native(sp.1[54], where = "Spain", region = "europe")
is_native(sp.1[55], where = "Spain", region = "europe")
is_native(sp.1[56], where = "Spain", region = "europe")
is_native(sp.1[57], where = "Spain", region = "europe")
is_native(sp.1[58], where = "Spain", region = "europe")
is_native(sp.1[59], where = "Spain", region = "europe")
is_native(sp.1[60], where = "Spain", region = "europe")
is_native(sp.1[61], where = "Spain", region = "europe")
is_native(sp.1[62], where = "Spain", region = "europe")
is_native(sp.1[63], where = "Spain", region = "europe")
is_native(sp.1[64], where = "Spain", region = "europe")
is_native(sp.1[65], where = "Spain", region = "europe")
is_native(sp.1[66], where = "Spain", region = "europe")
is_native(sp.1[67], where = "Spain", region = "europe")
is_native(sp.1[68], where = "Spain", region = "europe")
is_native(sp.1[69], where = "Spain", region = "europe")
is_native(sp.1[70], where = "Spain", region = "europe")
is_native(sp.1[71], where = "Spain", region = "europe")
is_native(sp.1[72], where = "Spain", region = "europe")
is_native(sp.1[73], where = "Spain", region = "europe")
is_native(sp.1[74], where = "Spain", region = "europe")
is_native(sp.1[75], where = "Spain", region = "europe")
is_native(sp.1[76], where = "Spain", region = "europe")
is_native(sp.1[77], where = "Spain", region = "europe")
is_native(sp.1[78], where = "Spain", region = "europe")
is_native(sp.1[79], where = "Spain", region = "europe")
is_native(sp.1[80], where = "Spain", region = "europe")
is_native(sp.1[81], where = "Spain", region = "europe")
is_native(sp.1[82], where = "Spain", region = "europe")
is_native(sp.1[83], where = "Spain", region = "europe")
is_native(sp.1[84], where = "Spain", region = "europe")
is_native(sp.1[85], where = "Spain", region = "europe")
is_native(sp.1[86], where = "Spain", region = "europe")
is_native(sp.1[87], where = "Spain", region = "europe")
is_native(sp.1[88], where = "Spain", region = "europe")
is_native(sp.1[89], where = "Spain", region = "europe")
is_native(sp.1[90], where = "Spain", region = "europe")
is_native(sp.1[91], where = "Spain", region = "europe")
is_native(sp.1[92], where = "Spain", region = "europe")
is_native(sp.1[93], where = "Spain", region = "europe")
is_native(sp.1[94], where = "Spain", region = "europe")
is_native(sp.1[95], where = "Spain", region = "europe")
is_native(sp.1[96], where = "Spain", region = "europe")
is_native(sp.1[97], where = "Spain", region = "europe")
is_native(sp.1[98], where = "Spain", region = "europe")
is_native(sp.1[99], where = "Spain", region = "europe")
is_native(sp.1[100], where = "Spain", region = "europe")
is_native(sp.1[101], where = "Spain", region = "europe")
is_native(sp.1[102], where = "Spain", region = "europe")
is_native(sp.1[103], where = "Spain", region = "europe")
is_native(sp.1[104], where = "Spain", region = "europe")
is_native(sp.1[105], where = "Spain", region = "europe")
is_native(sp.1[106], where = "Spain", region = "europe")
is_native(sp.1[107], where = "Spain", region = "europe")
is_native(sp.1[108], where = "Spain", region = "europe")
is_native(sp.1[109], where = "Spain", region = "europe")
is_native(sp.1[110], where = "Spain", region = "europe")
is_native(sp.1[111], where = "Spain", region = "europe")
is_native(sp.1[112], where = "Spain", region = "europe")
is_native(sp.1[113], where = "Spain", region = "europe")
is_native(sp.1[114], where = "Spain", region = "europe")
is_native(sp.1[115], where = "Spain", region = "europe")
is_native(sp.1[116], where = "Spain", region = "europe")
is_native(sp.1[117], where = "Spain", region = "europe")
is_native(sp.1[118], where = "Spain", region = "europe")
is_native(sp.1[119], where = "Spain", region = "europe")
is_native(sp.1[120], where = "Spain", region = "europe")
is_native(sp.1[121], where = "Spain", region = "europe")
is_native(sp.1[122], where = "Spain", region = "europe")
is_native(sp.1[123], where = "Spain", region = "europe")
is_native(sp.1[124], where = "Spain", region = "europe")
is_native(sp.1[125], where = "Spain", region = "europe")
is_native(sp.1[126], where = "Spain", region = "europe")
is_native(sp.1[127], where = "Spain", region = "europe")
is_native(sp.1[128], where = "Spain", region = "europe")
is_native(sp.1[129], where = "Spain", region = "europe")
is_native(sp.1[130], where = "Spain", region = "europe")
is_native(sp.1[131], where = "Spain", region = "europe")
is_native(sp.1[132], where = "Spain", region = "europe")
is_native(sp.1[133], where = "Spain", region = "europe")
is_native(sp.1[134], where = "Spain", region = "europe")
is_native(sp.1[135], where = "Spain", region = "europe")
is_native(sp.1[136], where = "Spain", region = "europe")
is_native(sp.1[137], where = "Spain", region = "europe")

